apiVersion: v1
kind: Service
metadata:
  name: eks-mm-fe-service
  namespace: mm
  labels:
    app: eks-mm-fe-app
spec:
  selector:
    app: eks-mm-fe-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
