apiVersion: v1
kind: Service
metadata:
  name: eks-haiku-service
  namespace: haiku
  labels:
    app: eks-haiku-app
spec:
  selector:
    app: eks-haiku-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
